os: linux
dist: jammy
group: dev
language: shell
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs18.x"  
  edge:
    branch: tbt_4_am
  on:
    branch: dpl_test
