os: linux
dist: jammy
group: dev
language: shell
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
deploy:
  provider: s3
  edge:
    branch: tbt_4_am
  on:
    branch: dpl_test
