os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: "U+19HgB/VyUjJ5CuP8jdHGv1dpRrvqsmG5uzwt/jo8xCxmqzOIkFQYJdxeF1wMknqsgIY5H5SNt6dOGTJjDzeagzCa8GNXEhvf7Isg8Esp5lEGm4R2tFVWc0UWLhAKQz8IQL6pVuuTD4mIebRxEHcAj8tA8SEKtEGb3mRqQWxXon8mSn+CMptPMHz0bT5yjyczKXIDZh7nvUZQxPbe6C35Yly+h8sqU/uDAQOmx1lrv4gLN/Xj7iPRoWrPY65y/3NXA9fmIFjo5M/1Z3tEMmYYoNuNGf3zUG2o0YLKMGXqyscDOLU9QDyBiKSWPEIbURAvCOJ4acP4amsRa95YqHd7t8pXrVJEwDOY1xJpaztC+INxszA2NUOSrhAUeu80dLROmc/E493xe3IP1OcmTst+uxYncd1QRbqwAqHL8HKM4iyYVS0700bQHqEWt1xfyKkwQuHx1JhFNETB3EcgC8IqVJOKEsJMrL+jO3XdIB+v3RGWEH/LdGZS6eGiwHIXZUk5VzQHJfueB9U28I0AMA5K+/bCbFXjtIGTQ2B9bYV+akEBw1KwXaxFXEkFuaQScZe0g/xAzl0hAaQDv2tIDL0ICY2a8oaFH3LG5Kj0kCKyyo3vBJAiiCaSX5MRTL3RNhOUNzW3lKPf2A3+odcwNZmp3tkWDKccRhQpqO4NrM93A="
    # BAR
    - secure: "Khr1NJ4rsJVza85xH3+chAYQ5FEpHq7SS2cE7+thX687ZBGmvqlN3825gWPZW7i4VNdj6je+A+342IV57pgiGLn7AQ6KeDMiNC3PwWN1k4VxdKZPJh7VEYvl9573va47wzoTsB2TpkKk4b23jcBy72KonH2l3SjmxhTH83ymHN9ILjs11FyrXNJMXcjSY5k+LxEk/AFDIUBGlXKDPtpw342Y7MeUrQ/x5egl/qdhuvsN8BL1OmeJ+hCEY8IJ8kAACa5FGvUCzFqSl4itkgz/3DTSZwXf5oZTXDWqCf0Fi2sYS/IFpOksukZck75S4q4dn5+n+3feY9fE3UM3y4khekmPVJmTIo4SKzF54a0snMtercT18+HHshMCOiP3QfU48SYnQVeJZ7VxzzI2bQvoPDZG5tfZpDwZ3Ae0LctjANFC53pWT875zFKAd3fHpkUD6bU+fCsbLCyS6qGsVX86W/yKqoFl0L6yhcLYUF5xjMbk7olpLinxPE7Y45D3b5YOnY2l8hYRg0U4IjqCK6RUqfVn40J/MstoPvAyXFEATAph+jc38OCX0qhYu7KSMSH5LNyy2o68uS5KJdNVIKFW/9Q5Mi0lgCMhxS2tjjx8jbbWEeF9uVIAuur02BSZxkLiECzTV4bYrdzpuzeZZz5JTG8+fJH8hUmXGztX/LiUE0Y="
jobs:
  include:
    - stage: "sleep 109"
      script: echo $FOO
