os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: "U+19HgB/VyUjJ5CuP8jdHGv1dpRrvqsmG5uzwt/jo8xCxmqzOIkFQYJdxeF1wMknqsgIY5H5SNt6dOGTJjDzeagzCa8GNXEhvf7Isg8Esp5lEGm4R2tFVWc0UWLhAKQz8IQL6pVuuTD4mIebRxEHcAj8tA8SEKtEGb3mRqQWxXon8mSn+CMptPMHz0bT5yjyczKXIDZh7nvUZQxPbe6C35Yly+h8sqU/uDAQOmx1lrv4gLN/Xj7iPRoWrPY65y/3NXA9fmIFjo5M/1Z3tEMmYYoNuNGf3zUG2o0YLKMGXqyscDOLU9QDyBiKSWPEIbURAvCOJ4acP4amsRa95YqHd7t8pXrVJEwDOY1xJpaztC+INxszA2NUOSrhAUeu80dLROmc/E493xe3IP1OcmTst+uxYncd1QRbqwAqHL8HKM4iyYVS0700bQHqEWt1xfyKkwQuHx1JhFNETB3EcgC8IqVJOKEsJMrL+jO3XdIB+v3RGWEH/LdGZS6eGiwHIXZUk5VzQHJfueB9U28I0AMA5K+/bCbFXjtIGTQ2B9bYV+akEBw1KwXaxFXEkFuaQScZe0g/xAzl0hAaQDv2tIDL0ICY2a8oaFH3LG5Kj0kCKyyo3vBJAiiCaSX5MRTL3RNhOUNzW3lKPf2A3+odcwNZmp3tkWDKccRhQpqO4NrM93A="
    # BAR
    - secure: "AaaOUb9aNy81RsPmLDvAe67Txf5zWewK1zdG+abuckAMDGHgqCULyKhrA3yVQzHyo3+scyjqEUfRaVwSv3+DXW9ff0qPfglVZJIY5eSsuy/tmR4xNrO0znMn4g5JTozHJhGvIo4zfOcJonT4sveTUNfKsRLWVtcHKB98NH/2nSSyreccZREzQ196CEtF3K8Eetssu7faZ7B5ys1/pc6dNan0eyMuCrBJY4Qh1RGTrtmmA9teeRt3OupiqmVTBP6hBbnVm2PU4EmM2GJWFl8QQBTwXCQnpe6jbAU6wPLcpRtcabfkN5Feg0TB2yXaeZnL82Q6K9Ey4Gb0s3yQUenHMzml5u9cdx4IknwAVby6WyrVCTm/nkQ5H4NYZJ+Ku+q0MwEFCPWS/59tLE7tTFu9l60UUI5sAAJct+LWZftqde/jWF1ifpAQE9nhWA6f1TaQsUMVhtfWOoO3dlCTaFGl9uAxrfuIPE+6ZMrPUzbl/rXMsuP7XyV9JLpjU7ON8hMV1GdaRERD2rBQJQtwaWBmPHANB2nEv+P/OHys2C276zeeNxReLaY56SP5vB82enOXh90r33eyWBx1UVIsd2tRKS2fIFqrGfX5Yli/os3UjjDQMxkbtRQSRRGan7GaEB7HXGtLhb/cw0rVEpoyra7Wc5bHOViWhiPlQNbhsqoYbfQ="
jobs:
  include:
    - stage: "sleep 109"
      script: echo $FOO
