os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: "mUWjEtlul0Feig1O47JhNHOvwHyGAi7vMdDEVsRkstD+S/kbWblszRXKkHpWMpSdDjvYCh4zokLeF6RvScCN/RiuEsgDtcLxTSHGzYv/r21Z8a8j/0QGzr/2RpXSe+2gcja7KSpnmKXAXNDDRNqdlTducSBLQZWStkLBFfRPIBG4G53KXfXPlG0oL947/0Eb3F/2YjR2H9lFZ6n9LKlaJ6cASmMKVNS0f79CCPr+OIAVwgMG2BYXeI2agfJVxzD/yYy51nKXCq6r7qW+QYPaT8hO068aXyT+K2KBJ+hGUiiQ7sNB2T8eCIpxE56QrX8wnEM968VCK91fNqzGW8N30/Wjh8W3CEQdmNRNlicSGV8XJ7HXqephyHt8mOom+YzQZXl9s4FyZqhOg/kZrHttwL8t75Xk/v16jLaGtrd3L5K6qUe59QHprDszwhdmTAiAO/mgeCEWnggdXddsn1rQLJhQeZDyHBoV+Lt0H9a795PL9JTNer4+jMd7HRQ7nKB5Bbf/O0p0XWgtmE5txM0JRH7AbBaQ/PVaIQo0EBIDC4GD02x8L/ED3WoWXGRKsenyBbv0VIcBcFqfz5CKpD81YuazH2m4PP9/bqmKo4Bun/o0ziVI2ZXFO/m6ozl9Yhtj1BBqpvn/bvYErWQg76bpqzPW7wJLsvAiK6euOIBKQDo="
jobs:
  include:
    - stage: "sleep 109"
      script: echo $FOO
