os: linux
arch: amd64
rvm: 2.6.3
env:
  global:
    # FOO
    - secure: "YoOKFb0hg/3kwA2H93tqmt/ezrOdhCk6WIBSTzA4hYC3o6pgmlvwSC5oaI+oTFKGh2pEDaxykBZ+hRfaUkNgnDIquaqTTtH0FjzO5VGRMSpXvMDABzGOgdBt3LvyG1GjxjnNEO1btfXsQFPp6yJiLctTv0c9XDnwJLi0abZgPWzUnS1Xn6iDLE/qH3mcF81til5FiMyp1o33nIb1VDdSJBlNi57yogaUrTCp0C1WghKVYIG9kqY2hPFJqNDOessngU0XYrog3dNYeN6o1c++mEnfWXnPGSdiuGEcBMuE1TzvUeDlC3J67+bVg6ohSfFZe10qeAKzkT7fslMUhMJ0DRpxMLvQk8Sy7LHqqfn7n6/JtAD2gBH5Kg8wPd4bMF8J1I6prx9m8PnhGD5qgiBC85hIQxpRoqNmiHkd3hWeo0I4X0SDBAwrRjutFi3ZjHPndCnlU15VhPILE/ARN1weyCeUce/G6jE7kCfDEhj9w9tm1pMm88yoc18zvOYzyTB2sz7jiKG8h2PCwRnMafSrVUrqO90EhuGiB16wxQzEFFirWynM2iXDBu00fje9JOfHTGiycD6UDRUGhzCMdLbDcgCO4aP5lr3pGQGi2cUBf+KNmzJbHx+WbU/4VSh2zB/3mwsDYnTV7/6xodOGyrcTVe0/3I3Vm9DZjAhJ/2Aqej4="
    # BAR
    - secure: "rFTePuQTU5AYD33rtta8DMbwHle7D5xvgqvxKQSQKHs/8b9jp9PYtXb1XlbIcCRE61o7Th3I0G5XPZxrkMro14SAih8KkxAvbc3TMZX+RYFDx+yCYvYgZzJtzhWAAXyQ6ZSvG09thX8WL1/ua7870hseNlqMk8fTEKp0/yd+wtl0tGbTUsTp8We7NL3KIfZqZNSc16aLezqB3eb2tEO/HzXRbUtTZLmiPLrZlYqoH42kW/RZBni9CnqzxvYgDvTSBqb0LWkcHQymr85eaBphok/w3rFeLrI5y0IuURQyCIbUMMvUHbiJep6GUW63ACMQE0Vyd3EHCFfag6xgSmLVWX+BBA+25LT/zZswij4D3PoX03zSiDQAaPFu2UYcKGgkEdZ/ameSNwHDjkkeJAIBtjHzLKp9XQcNG3W1b0lzimnw/9LPj56wEd8i7AvFmmJVlx2a+7vHTn74/l5u1P9+swjdbclGoK1bDiRYbFCTfrzBxUJknkl8DAy3ZzGnKCUPYiaHPsvwvamFX+D8HO8dUx6XCauYXeSvAyTxhZzhbWUu0Chd1bnAhX5RffYlQpZ9kAqFVTMcElwMjGtF8RqoQDpuA1zNiILXn2X0KHY/ktn2iaC9uHw5Z0xgAVNcxhjDYBfVsm3W+GzQ6bARj6qOenRJUmvCzV8sgKe5ad6PH20="
jobs:
  include:
    - stage: "sleep 109"
      script: echo $FOO
