os: linux
dist: jammy
group: dev
language: shell
script:
  - rvm pkg install openssl && rvm reinstall ruby-2.7.8 --with-openssl-dir=$HOME/.rvm/usr
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_EVENT_TYPE
deploy:
#  dpl_version: 1.10.16
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  role: "arn:aws:iam::341288657826:role/lambda_basic_execution"
  runtime: "nodejs18.x"
  handler_name: "main"
#  edge:
#    branch: tbt_4_am
  on:
    branch: dpl_test
